name: Deploy to ghcr.io
on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/westelh/discord-notification:test
          outputs: type=docker,dest=/tmp/discord-notification.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: discord-notification
          path: /tmp/discord-notification.tar
