name: 'CI Test'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/westelh/discord-notification:test
          outputs: type=docker,dest=/tmp/discord-notification.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: discord-notification
          path: /tmp/discord-notification.tar

  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: discord-notification
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/discord-notification.tar
          docker image ls -a

      - name: Run
        run: docker run -e APIPATH=${{secrets.APIPATH}} -e HOSTNAME=Actions ghcr.io/westelh/discord-notification:test

  

